services:
  postgres:
    image: postgres:17
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce_dw
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      LANG: en_US.utf8
      LC_ALL: en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ecommerce_dw"]
      interval: 5s
      timeout: 5s
      retries: 10

  metabase:
    image: metabase/metabase:latest
    container_name: ecommerce_metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ecommerce_dw
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin
      MB_DB_HOST: postgres
      JAVA_OPTS: -Duser.timezone=UTC
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - metabase_data:/metabase-data

volumes:
  postgres_data:
  metabase_data: